---
title: "Homework 4"
author: "Regan Honeycutt"
date: "2/10/2022"
output: html_document
---

``` {R}
install.packages("vegan")
library(vegan)


library(vegan)
data(dune)
data(dune.env)
dune
```





Conduct an indirect ordination on the dune plant community. Specifically, visually examine a NMDS plot using the bray-curtis distance metric. Below is some code to help you develop a potential plot that emphasizes the role of the environmental variable “Moisture”. Describe how you interpret the graphic. What is the goal of creating such a plot? Does this analysis suggest any interesting findings with respect to the dune vegetation?

```{R}

dune_mds <- metaMDS(dune)

 plot(dune_mds, type='n')
 text(dune_mds, 'sp', cex=.5)
 # generate vector of colors 
 color_vect = rev(terrain.colors(6))[-1]
 points(dune_mds, 'sites', pch=19, 
        col=color_vect[dune.env$Moisture])
 legend('topright', paste("Moisture =", 1:5, sep=''), 
        col=color_vect, pch=19)
        
```        
    This plot shows which species occur with which moisture levels. This plot provides a quick and preliminary summary of the data. This graph suggests that dune vegetation varies across moisture levels. 
        
        
        
        
Carry out a direct ordination using CCA in order to test any potential hypotheses that you developed after examining the MDS plot. Specifically, carry out a test of the entire model (i.e., including all constrained axes) and also carry out tests at the scale of individual explanatory variables you included in your model if you included more than one variable. Plot your results.

```{r}

cca_moisture = cca(dune ~ Moisture , data = dune.env)
RsquareAdj(cca_moisture, 100)

cca_dune = cca(dune, dune.env$A1, dune.env$Moisture, dune.env$Management, dune.env$Use, dune.env$Manure, data = dune.env)
RsquareAdj(cca_dune)

cca_A1 = cca(dune ~ A1 , data = dune.env)
RsquareAdj(cca_A1, 100)
cca_management = cca(dune ~ Management, data = dune.env)
RsquareAdj(cca_management, 100)
cca_use = cca(dune ~ Use , data = dune.env)
RsquareAdj(cca_use, 100)
cca_manure = cca(dune ~ Manure , data = dune.env)
RsquareAdj(cca_manure, 100)

plot(cca_dune)

```
Note: management, moisture, and manure have highest R^2

Do your two analyses agree with one another or complement one another or do these two analyses seem to be suggesting different take home messages? Which analysis do you find to be more useful?


The two analyses agree with one another because the moisture (and the management) are high R-squared values and similar adjusted R-squared values. I found the CCA analysis to be the most useful in understanding the specifics of the data, but the NMDS plot was most useful in simply visualizing the data. 







